### ISSUE TITLE
get rid of QA warning

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#102]
> WARNING: QA Issue: linux-yocto-efi-test: Files/directories were installed but not shipped in any package:
>   /lib/modules/4.7.0-yocto-standard/kernel/drivers/acpi
> Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
> linux-yocto-efi-test: 1 installed and not shipped files. [installed-vs-shipped]

This may be coming from linux-yocto-efi-test as we delete this directory to not install the actual nfit.ko to be able to install its testing version.

**Comment by meghadey** [comment]
This issue has been fixed as part of https://lists.01.org/pipermail/luv/2017-January/001512.html
