### ISSUE TITLE
Get rid of License warnings in linux firmware

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#103]
> WARNING: LICENSE_linux-firmware-ralink-license includes licenses (Firmware-ralink-firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-ralink includes licenses (Firmware-ralink-firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-radeon-license includes licenses (Firmware-radeon) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-radeon includes licenses (Firmware-radeon) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-marvell-license includes licenses (Firmware-Marvell) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-sd8686 includes licenses (Firmware-Marvell) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-sd8688 includes licenses (Firmware-Marvell) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-sd8787 includes licenses (Firmware-Marvell) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-sd8797 includes licenses (Firmware-Marvell) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-ti-connectivity-license includes licenses (Firmware-ti-connectivity) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-wl12xx includes licenses (Firmware-ti-connectivity) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-wl18xx includes licenses (Firmware-ti-connectivity) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-vt6656-license includes licenses (Firmware-via_vt6656) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-vt6656 includes licenses (Firmware-via_vt6656) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-rtl-license includes licenses (Firmware-rtlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-rtl8192cu includes licenses (Firmware-rtlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-rtl8192ce includes licenses (Firmware-rtlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-rtl8192su includes licenses (Firmware-rtlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-broadcom-license includes licenses (Firmware-broadcom_bcm43xx) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-bcm4329 includes licenses (Firmware-broadcom_bcm43xx) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-bcm4330 includes licenses (Firmware-broadcom_bcm43xx) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-bcm4334 includes licenses (Firmware-broadcom_bcm43xx) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-bcm43340 includes licenses (Firmware-broadcom_bcm43xx) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-bcm4339 includes licenses (Firmware-broadcom_bcm43xx) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-bcm43430 includes licenses (Firmware-broadcom_bcm43xx) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-bcm4354 includes licenses (Firmware-broadcom_bcm43xx) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-atheros-license includes licenses (Firmware-atheros_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-ar9170 includes licenses (Firmware-atheros_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-ath6k includes licenses (Firmware-atheros_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-ath9k includes licenses (Firmware-atheros_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-ar3k-license includes licenses (Firmware-qualcommAthos_ar3k) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-ar3k includes licenses (Firmware-qualcommAthos_ar3k) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-ath10k-license includes licenses (Firmware-qualcommAthos_ath10k) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-ath10k includes licenses (Firmware-qualcommAthos_ath10k) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-license includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-135-6 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-3160-7 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-3160-8 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-3160-9 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-6000-4 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-6000g2a-5 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-6000g2a-6 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-6000g2b-5 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-6000g2b-6 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-6050-4 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-6050-5 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-7260 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-7265 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-7265d includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-8000c includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-8265 includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-iwlwifi-misc includes licenses (Firmware-iwlwifi_firmware) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-i915-license includes licenses (Firmware-i915) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-i915 includes licenses (Firmware-i915) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-adsp-sst-license includes licenses (Firmware-adsp_sst) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-adsp-sst includes licenses (Firmware-adsp_sst) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-bnx2-mips includes licenses (WHENCE) that are not listed in LICENSE
> WARNING: LICENSE_linux-firmware-whence-license includes licenses (WHENCE) that are not listed in LICENSE

**Comment by meghadey** [comment]
We are seeing these warning because we are overwriting the "LICENSE" variable but not the "PACKAGES" variable in the .bbappend file in the meta-layer. As such, bitbake does not find the corresponding LICENSES listed for the various packages.

Overwriting the "PACKAGE" variable to just  "${PN}-license \" resolves this issue.

**Comment by meghadey** [comment]
Patch which fixes this issue can be found here:
https://lists.01.org/pipermail/luv/2017-November/002314.html
