### ISSUE TITLE
Default LUV_STORAGE to not be used

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#105]
The LUV_STORAGE has a placeholder for the URL format it expects of the server used to collect test results. We should disable LUV_STORAGE by default and clearly indicate that it is not used. Maybe it can be done by putting LUV_STORAGE=no and have the script that parses it (save_netboot_results) to exit if it is disabled.

**Comment by meghadey** [comment]
issue fixed as part of https://lists.01.org/pipermail/luv/2017-January/001496.html

**Comment by gkammela** [comment]
Setting LUV_STORAGE_URL to none by default is implemented here https://lists.01.org/pipermail/luv/2017-March/001725.html
