### ISSUE TITLE
Recipes that depend on the kernel fail to find their files

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#106]
Several of our recipes utilize the same codebase as the kernel. This is, they not only depend on virtual/kernel but use the same files. This has unexpected consequences when cleaning files. For instance, if we do

bitbake luv-yocto-efi-test
bitbake efivarfs-test
bitbake -c cleanall efivarfs-test
bitbake efivarfs-test

bitbake will complain that tools/testing/selftests/efivarfs/efivarfs.sh does not exist.

This happens because the S directory in the efivarfs-test recipe is STAGING_KERNEL_DIR, which gets deleted with cleanall.

I am not sure what is the right solution. Perhaps, a missing dependency?

**Comment by meghadey** [comment]
This issue is being tracked as part of https://github.com/01org/luv-yocto/issues/112 . Hence closing this as it is a duplicate.
