### ISSUE TITLE
Ship .config file with LUV

### ISSUE THREAD

**Issue by prakhya** [01org/luv-yocto#108]
Presently, we don't ship ".config" file with luv-live-image but it would be handy if we could provide the ".config" file that is used to build kernel in LUV. So, that one could easily see what the kernel is made of and maybe can tweak some kernel config options and build kernel with that and can replace the provided LUV kernel.

**Comment by meghadey** [comment]
This issue has been fixed. https://lists.01.org/pipermail/luv/2016-December/001381.html for more details.

**Comment by ricardon** [comment]
Config file can be retrieved from /proc/config.gz in a running system. It would also be good to include in the bootable image.
