### ISSUE TITLE
Add a parser to check for EFI_MEMORY_ATTRIBUTES failure

### ISSUE THREAD

**Issue by prakhya** [01org/luv-yocto#110]
UEFI v2.6 specification describes EFI_MEMORY_ATTRIBUTES_TABLE and since kernel (both x86 and ARM) has support for this feature, it's good to have a parser that looks around for any failures that might have occurred while kernel parsing this table or when kernel is updating it's page attributes according to this table.

**Comment by ricardon** [comment]
This could be added here with liitle effort: meta-luv/recipes-core/kernel_efi_warnings/kernel-efi-warnings/kernel-efi-warnings

**Comment by ricardon** [comment]
@prakhya implemented this.
