### ISSUE TITLE
Unify common parts of luv-live-image.bb and luv-netboot-image.bb

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#114]
We currently maintain two recipes for live images. luv-live-image.bb is used to generate disk images. luv-netboot-image is to generate an EFI application image that can be booted via network.

While there are details that differ among these recipes, some parameters are similar. It would be good to have all these similarities in a common luv.inc file. Things to look at:

1)Linux command line, which variesonly slightly. 
2)Common inherit instances
3) setting the EFI_USEXORRISO variable
4) splash image
5) INITRD_IMAGE_LIVE and related variables

**Comment by meghadey** [comment]
have a .inc file to have the common features.

**Comment by meghadey** [comment]
Patch which fixes this issue can be found here:
https://lists.01.org/pipermail/luv/2017-November/002266.html
