### ISSUE TITLE
Dump boot dmesg into a file

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#117]
kmsg contains lots of interesting information that is useful for debug and profiling the system under test. IT would be good to put it in a a file for post-mortem analysis.

**Comment by Manouchehri** [comment]
Might want to expand the luv-results partition (#99), dmesg can get noisy.

**Comment by ricardon** [comment]
@prakhya has implemented this. @Manouchehri in our tests we did not see the luv-results partition filling up. Also, LUV will check if it has sufficient space before running test. We can revisit in the future if the need arises.
