### ISSUE TITLE
Results are overwritten by horizontal line in luv.html file

### ISSUE THREAD

**Issue by prakhya** [01org/luv-yocto#118]
On some specific machines; when LUV runs, the results in luv.html are overwritten by horizontal lines (as shown in the attachment). This happens because, chipsec dumps hex data and that data; when converted to ASCII, represents (<s), which means a horizontal line and hence the html file has horizontal lines overwriting results. When this specific character (<s) is replaced by something else, the results are normal (as shown in the attachment). One probable fix to this issue is to search chipsec hex dump for this character and escape it.
![overwritten_results](https://cloud.githubusercontent.com/assets/10333447/23978754/ef327adc-09b2-11e7-9f1e-0e8008248b9b.png)
![normal_results](https://cloud.githubusercontent.com/assets/10333447/23978759/f14d0b52-09b2-11e7-9469-893ebbfe4fa9.png)

**Comment by meghadey** [comment]
use sed to escape the '<' sign in the chipsec output while running the parser.

**Comment by meghadey** [comment]
Patch which fixes this issue can be found here:
https://lists.01.org/pipermail/luv/2018-January/002425.html
