### ISSUE TITLE
v2.1-rc2 missing from 01.org

### ISSUE THREAD

**Issue by Manouchehri** [01org/luv-yocto#122]
On https://01.org/linux-uefi-validation/downloads, v2.1-rc1 is still listed as the current release.

Might want to push v2.1-rc2, or redirect the downloads page on 01.org to GitHub.

**Comment by ricardon** [comment]
Yes, I have been pondering what you say. It is somewhat painful updating 01.org. But you are right, clarification needs to be made.

**Comment by Manouchehri** [comment]
@ricardon maybe just update 01.org once to point people here?

**Comment by ricardon** [comment]
I have updated https://01.org/linux-uefi-validation/downloads to contain both v2.1-rc2 and v2.1 release images. Thanks!
