### ISSUE TITLE
Network issue delays running the testsuites in luv-netboot-image

### ISSUE THREAD

**Issue by gkammela** [01org/luv-yocto#124]
Even after the interface link ready(according to dmesg), luv-netboot-image takes ~250 secs to start running the testsuites. This can be mistaken for a system hang and hence needed a fix.

**Comment by ricardon** [comment]
Probably this problem can be debugged using the systemd-analyze tool. Luckily, this tool is already in poky. All we have to do is add it to the ramdisk image by adding systemd-analyze.

Useful references:
https://debian-administration.org/article/722/Analysing_performance_problems_with_systemd
https://wiki.archlinux.org/index.php/Improving_performance/Boot_process#Using_systemd-analyze

**Comment by meghadey** [comment]
Patch which fixes this issue can be found here:
https://lists.01.org/pipermail/luv/2017-November/002315.html
