### ISSUE TITLE
LUV incorrectly reports MTRR across all processors are inconsistent

### ISSUE THREAD

**Issue by niruiyu** [01org/luv-yocto#127]
When running LUV in a multiple-core system, below failures are seen:

;INF Test 2 of 3: Validate the MTRR setup across all processors.
;INF Detected CPUs with inconsistent variable MTRR settings which
;INF the kernel fixed.
;FAL FAILED [MEDIUM] MTRRCPUsMisconfigured: Test 2, It is
;FAL probable that the BIOS does not set up all the CPUs
;FAL correctly and the kernel has now corrected this
;FAL misconfiguration.

The failure is because LUV detects that the MTRR register contents are different in all processors.

Per IA32 SDM, a pair of MTRR registers (Base/Mask) is considered as valid when Mask.Valid equals to 1. When Mask.Valid equals to 0, the Base register content is ignored.

The failure reported by LUV is not a real failure. The Mask.Valid equals to 0 for the pairs of MTRR registers that are different. The differences don't cause the memory cache settings differ in all processors.

I think LUV test case should be updated to compare the memory cache settings between in all processors, but not compare the raw MTRR registers.

**Comment by meghadey** [comment]
Patch which fixes this issue can be found here:
https://lists.01.org/pipermail/luv/2017-November/002335.html
