### ISSUE TITLE
input argument report issue

### ISSUE THREAD

**Issue by Laurence-Zhou-defu** [01org/luv-yocto#128]
error report

1.1 18:23:22:896112715 fwts syntaxcheck INFO ;NLN 
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF Checking ACPI table SSDT (#1)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;NLN 
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;FAL FAILED [LOW] AMLAsmUnknown: Test 1, Assembler remark in line
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;FAL 88
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF Line | AML source
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;SEP ------------------------------------------------------------
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00085|                 Return (0x0F)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00086|             }
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00087| 
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00088|             Method (HINF, 3, Serialized)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF      |                       ^
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF      | Remark 2146: Method Argument is never used    (Arg0)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00089|             {
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00090|                 Switch (ToInteger (Arg1))
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00091|                 {
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;SEP ============================================================
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;FAL FAILED [LOW] AMLAsmUnknown: Test 1, Assembler remark in line
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;FAL 88
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF Line | AML source
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;SEP ------------------------------------------------------------
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00085|                 Return (0x0F)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00086|             }
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00087| 
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00088|             Method (HINF, 3, Serialized)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF      |                       ^
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF      | Remark 2146: Method Argument is never used    (Arg2)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00089|             {
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00090|                 Switch (ToInteger (Arg1))
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00091|                 {
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;SEP ============================================================
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;FAL FAILED [LOW] AMLAsmUnknown: Test 1, Assembler remark in line
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;FAL 144
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF Line | AML source
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;SEP ------------------------------------------------------------
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00141|                 Zero, 
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00142|                 Zero
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00143|             })
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00144|             Method (TPPI, 3, Serialized)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF      |                       ^
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF      | Remark 2146: Method Argument is never used    (Arg0)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00145|             {
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00146|                 Switch (ToInteger (Arg1))
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00147|                 {
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;SEP ============================================================
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;FAL FAILED [LOW] AMLAsmUnknown: Test 1, Assembler remark in line
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;FAL 218
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF Line | AML source
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;SEP ------------------------------------------------------------
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00215|                 Return (One)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00216|             }
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00217| 
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00218|             Method (TMCI, 3, Serialized)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF      |                       ^
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF      | Remark 2146: Method Argument is never used    (Arg0)
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00219|             {
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00220|                 Switch (ToInteger (Arg1))
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;INF 00221|                 {
1.1 18:23:22:896112715 fwts syntaxcheck INFO ;SEP ============================================================

source code

/**@file

@copyright
 Copyright (c) 2012 - 2015 Intel Corporation. All rights reserved
 This software and associated documentation (if any) is furnished
 under a license and may only be used or copied in accordance
 with the terms of the license. Except as permitted by the
 license, no part of this software or documentation may be
 reproduced, stored in a retrieval system, or transmitted in any
 form or by any means without the express written consent of
 Intel Corporation.
 This file contains an 'Intel Peripheral Driver' and is uniquely
 identified as "Intel Reference Module" and is licensed for Intel
 CPUs and chipsets under the terms of your license agreement with
 Intel or your vendor. This file may be modified by the user, subject
 to additional terms of the license agreement.

@par Specification
**/
/** @file
  The TPM2 definition block in ACPI table for TrEE physical presence  
  and MemoryClear.
**/

DefinitionBlock (
  "Tpm.aml",
  "SSDT",
  1,
  "Intel_",
  "Tpm2Tabl",
  0x1000
  )
{
  External(TPMA)    
  External(TPML)    
  Scope (\_SB)
  {
    Device (TPM)
    {
      //
      // TREE
      //
      Name (_HID, "MSFT0101")
      
      //
      // Readable name of this device, don't know if this way is correct yet
      //
      Name (_STR, Unicode ("TPM 2.0 Device"))

      //
      // Return the resource consumed by TPM device
      //
      Name (TPMF, ResourceTemplate ()
      {
        Memory32Fixed (ReadWrite, 0x00000000, 0x00001000, BAR0)  
      })

      Method (_CRS, 0x0, Serialized) 
      {
         CreateDwordField(^TPMF, ^BAR0._BAS, TB0A)
         CreateDwordField(^TPMF, ^BAR0._LEN, TB0L)
         Store(TPMA, TB0A)
         Store(TPML, TB0L)
         Return (TPMF)  
      }
      OperationRegion (TICR, SystemMemory, 0xE00D0000, 0x100)
      Field (TICR, AnyAcc, NoLock, Preserve)
      { 
        Offset(0x8C),
        STAT, 32,
      }
      //
      // Operational region for Smi port access
      //
      OperationRegion (SMIP, SystemIO, 0xB2, 1)
      Field (SMIP, ByteAcc, NoLock, Preserve)
      { 
          IOB2, 8
      }

      //
      // Operational region for TPM support, TPM Physical Presence and TPM Memory Clear
      // Region Offset 0xFFFF0000 and Length 0xF0 will be fixed in C code.
      //
      OperationRegion (TNVS, SystemMemory, 0xFFFF0000, 0xF0)
      Field (TNVS, AnyAcc, NoLock, Preserve)
      {
        PPIN,   8,  //   Software SMI for Physical Presence Interface
        PPIP,   32, //   Used for save physical presence paramter
        PPRP,   32, //   Physical Presence request operation response
        PPRQ,   32, //   Physical Presence request operation
        LPPR,   32, //   Last Physical Presence request operation
        FRET,   32, //   Physical Presence function return code
        MCIN,   8,  //   Software SMI for Memory Clear Interface
        MCIP,   32, //   Used for save the Mor paramter
        MORD,   32, //   Memory Overwrite Request Data
        MRET,   32  //   Memory Overwrite function return code
      }

      Method (PTS, 1, Serialized)
      {  
        //
        // Detect Sx state for MOR, only S4, S5 need to handle
        //
        If (LAnd (LLess (Arg0, 6), LGreater (Arg0, 3)))
        {   
          //
          // Bit4 -- DisableAutoDetect. 0 -- Firmware MAY autodetect.
          //
          If (LNot (And (MORD, 0x10)))
          {
            //
            // Triggle the SMI through ACPI _PTS method.
            //
            Store (0x02, MCIP)
              
            //
            // Triggle the SMI interrupt
            //
            Store (MCIN, IOB2)
          }
        }
        Return (0)
      }   

      Method (_STA, 0)
      {
        Return (0x0f)
      }

      //
      // TCG Hardware Information
      //
      Method (HINF, 3, Serialized, 0, {BuffObj, PkgObj}, {UnknownObj, UnknownObj, UnknownObj}) // IntObj, IntObj, PkgObj
      {
        //
        // Switch by function index
        //
        Switch (ToInteger(Arg1))
        {
          Case (0)
          {
            //
            // Standard query
            //
            Return (Buffer () {0x03})
          }
          Case (1)
          {
            //
            // Return failure if no TPM present
            //
            Name(TPMV, Package () {0x01, Package () {0x2, 0x0}})
            if (LEqual (_STA (), 0x00))
            {
              Return (Package () {0x00})
            }

            //
            // Return TPM version
            //
            Return (TPMV)
          }
          Default {BreakPoint}
        }
        Return (Buffer () {0})
      }

      Name(TPM2, Package (0x02){
        Zero, 
        Zero
      })

      Name(TPM3, Package (0x03){
        Zero, 
        Zero,
        Zero
      })

      //
      // TCG Physical Presence Interface
      //
      Method (TPPI, 3, Serialized, 0, {BuffObj, PkgObj, IntObj, StrObj}, {UnknownObj, UnknownObj, UnknownObj}) // IntObj, IntObj, PkgObj
      {        
        //
        // Switch by function index
        //
        Switch (ToInteger(Arg1))
        {
          Case (0)
          {
            //
            // Standard query, supports function 1-8
            //
            Return (Buffer () {0xFF, 0x01})
          }
          Case (1)
          {
            //
            // a) Get Physical Presence Interface Version
            //
            Return ("1.2")
          }
          Case (2)
          {
            //
            // b) Submit TPM Operation Request to Pre-OS Environment
            //
                  
            Store (DerefOf (Index (Arg2, 0x00)), PPRQ)
            Store (0x02, PPIP)
              
            //
            // Triggle the SMI interrupt
            //
            Store (PPIN, IOB2)
            Return (FRET)

          }
          Case (3)
          {
            //
            // c) Get Pending TPM Operation Requested By the OS
            //
                  
            Store (PPRQ, Index (TPM2, 0x01))
            Return (TPM2)
          }
          Case (4)
          {
            //
            // d) Get Platform-Specific Action to Transition to Pre-OS Environment
            //
            Return (2)
          }
          Case (5)
          {
            //
            // e) Return TPM Operation Response to OS Environment
            //
            Store (0x05, PPIP)
                  
            //
            // Triggle the SMI interrupt
            //
            Store (PPIN, IOB2)
                  
            Store (LPPR, Index (TPM3, 0x01))
            Store (PPRP, Index (TPM3, 0x02))

            Return (TPM3)
          }
          Case (6)
          {

            //
            // f) Submit preferred user language (Not implemented)
            //

            Return (3)

          }
          Case (7)
          {
            //
            // g) Submit TPM Operation Request to Pre-OS Environment 2
            //
            Store (7, PPIP)
            Store (DerefOf (Index (Arg2, 0x00)), PPRQ)
                
            //
            // Triggle the SMI interrupt 
            //
            Store (PPIN, IOB2)  
            Return (FRET)
          }
          Case (8)
          {
            //
            // e) Get User Confirmation Status for Operation
            //
            Store (8, PPIP)
            Store (DerefOf (Index (Arg2, 0x00)), PPRQ)
                  
            //
            // Triggle the SMI interrupt
            //
            Store (PPIN, IOB2)
                  
            Return (FRET)
          }

          Default {BreakPoint}
        }
        Return (1)
      }

      Method (TMCI, 3, Serialized, 0, IntObj, {UnknownObj, UnknownObj, UnknownObj}) // IntObj, IntObj, PkgObj
      {
        //
        // Switch by function index
        //
        Switch (ToInteger (Arg1))
        {
          Case (0)
          {
            //
            // Standard query, supports function 1-1
            //
            Return (Buffer () {0x03})
          }
          Case (1)
          {
            //
            // Save the Operation Value of the Request to MORD (reserved memory)
            //
            Store (DerefOf (Index (Arg2, 0x00)), MORD)
                  
            //
            // Triggle the SMI through ACPI _DSM method.
            //
            Store (0x01, MCIP)
                  
            //
            // Triggle the SMI interrupt
            //
            Store (MCIN, IOB2)
            Return (MRET)
          }
          Default {BreakPoint}
        }
        Return (1)        
      }

      Method (TSMI, 3, Serialized, 0, IntObj, {UnknownObj, UnknownObj, UnknownObj}) // IntObj, IntObj, PkgObj
      {
        //
        // Switch by function index
        //
        Switch (ToInteger (Arg1))
        {
          Case (0)
          {
            //
            // Standard query, supports function 1-1
            //
            Return (Buffer () {0x03})
          }
          Case (1)
          {
            Store(0x00000001,STAT)
            Return (0)
          }
          Default {BreakPoint}
        }
        Return (1)        
      }

      Method (_DSM, 4, Serialized, 0, UnknownObj, {BuffObj, IntObj, IntObj, PkgObj})
      {

        //
        // TCG Hardware Information
        //
        If(LEqual(Arg0, ToUUID ("cf8e16a5-c1e8-4e25-b712-4f54a96702c8")))
        {
          Return (HINF (Arg1, Arg2, Arg3))
        }

        //
        // TCG Physical Presence Interface
        //
        If(LEqual(Arg0, ToUUID ("3dddfaa6-361b-4eb4-a424-8d10089d1653")))
        {
          Return (TPPI (Arg1, Arg2, Arg3))
        }

        //
        // TCG Memory Clear Interface
        //
        If(LEqual(Arg0, ToUUID ("376054ed-cc13-4675-901c-4756d7f2d45d")))
        {
          Return (TMCI (Arg1, Arg2, Arg3))
        }

        //
        // TPM2 ACPI Start Method
        //
        If(LEqual(Arg0, ToUUID ("6bbf6cab-5463-4714-b7cd-f0203c0368d4")))
        {
          Return (TSMI (Arg1, Arg2, Arg3))
        }

        Return (Buffer () {0})
      }
    }    
  }
}

the argument that remarked just a input,but report show a fail,
I doubt it is a bug，please give me some advices，thanks

**Comment by prakhya** [comment]
This message comes from the iASL compiler which is used in FWTS. This is just a remark from the compiler and does not imply an error. It’s more of a ASL code style warning. - As suggested by Erik.
So, probably you could ignore it or alternatively we will see if there's any config option in FWTS to ignore this check.

**Comment by meghadey** [comment]
It is better to leave this as a failure as the right arguments are not being passed. Closing this issue.
