### ISSUE TITLE
Sometimes luv.results presents two unit tests results in the same line

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#25]
For instance: the output of luv.results will look like:

```
  [+] uefirtvariable...     [-] kernel-efi-warnings
  [+] EFI_BOOT_SERVICES_*_illegal_access... 1 failures!
```

This happens because luv-test-parser only prints the new-line character ("\n") along with %d failures/passed/skipped/ if it can find a line like
1.0 testsuite testname_x RESULT n n n n
after finding one or more lines like:
1.0 testsuite testname_x INFO test description.

Thus, if any given test suite does not produces a line with the RESULT token, the following unit test will be writen in the same line because the (\n) was never written.

**Comment by meghadey** [comment]
Fixed
