### ISSUE TITLE
Long delays while booting luv live image

### ISSUE THREAD

**Issue by mfleming** [01org/luv-yocto#26]
Users are reporting seeing "Falling back to luv" and then having to wait a supremely long time for the blue splash screen to appear, like it's running off a :floppy_disk: or something.

@WilliamLeara reported having to wait 10-12 minutes for the blue splash screen to appear.

Something is very seriously fishy, :fish:

What we need is some means of figuring out where time is going for the entire boot process. #24 gets us some of the way there, if the user has a serial console setup (unlikely).

**Comment by meghadey** [comment]
seems to be fixed over time. Not been observed for a long time.
