### ISSUE TITLE
Tests suites that are executed needs to be configurable.

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#29]
Currently, LUV executes are the test suites that are included in the image at build time. However, this can be time-consuming and the user may not need/wish to run all the test suites as he/she would only be interested in a particular subset. This configuration scheme should meet the following criteria:
- Suites selected for execution should be configurable at boot time.
- The selected method should allow for automation and deployment over network.

**Comment by meghadey** [comment]
use the already present luv.cfg for choose which test-suites to run

**Comment by meghadey** [comment]
Patches fixing this issue can be found here:
https://lists.01.org/pipermail/luv/2017-November/002361.html
https://lists.01.org/pipermail/luv/2017-November/002362.html
https://lists.01.org/pipermail/luv/2017-November/002363.html
