### ISSUE TITLE
We need a wrapper script to automatically setup build env

### ISSUE THREAD

**Issue by mfleming** [01org/luv-yocto#31]
There are a number of steps required to configure the luv-yocto development environment correctly, and it's really easy to miss one, which results in a non-working system as demonstrated in issue #30.

Other projects based on the Yocto Project provide a wrapper script that does all the necessary configuration. We should be doing something similar.

Having this done in a wrapper script would also make it much, much simpler to perform automated builds from a fresh clone of the git repository, which is something we should be moving towards.

**Comment by meghadey** [comment]
Patch which fixes this issue can be found here:
https://lists.01.org/pipermail/luv/2018-January/002502.html
