### ISSUE TITLE
Send OVMF recipe to the Yocto Project

### ISSUE THREAD

**Issue by mfleming** [01org/luv-yocto#34]
There's a bugzilla entry open upstream for sending the OVMF recipe that we're carrying in the meta-luv layer to the Yocto Project.

https://bugzilla.yoctoproject.org/show_bug.cgi?id=5654

**Comment by meghadey** [comment]
@ricardon Are we planning to still upstream the OVMF recipe?

**Comment by ricardon** [comment]
Yes, Patrick Ohly is working on that: http://lists.openembedded.org/pipermail/openembedded-core/2017-January/131903.html

**Comment by ricardon** [comment]
This work is complete.
