### ISSUE TITLE
EFI pstore kernel selftests

### ISSUE THREAD

**Issue by mfleming** [01org/luv-yocto#35]
There are currently no tests to ensure that the CONFIG_EFIVARS_PSTORE code works correctly in the kernel. In fact, there have been occasions when it hasn't worked correctly.

Since this code has suffered from "drive-by" patches where one person works on the code for a while then disappears, we need a comprehensive set of tests to ensure that regressions are not introduced as the code is refactored. Of particular help would be pthread-based tests to check for race conditions in the code.

**Comment by ricardon** [comment]
@meghadey could you take a look at this?

**Comment by meghadey** [comment]
This is fixed in luv-2.2-c1
