### ISSUE TITLE
FWTS: Unittest 'cpufreq' takes pretty long to run on Haswell

### ISSUE THREAD

**Issue by gkammela** [01org/luv-yocto#36]
Test suite FWTS takes nearly 420 seconds approx (7 minutes) when tested on Haswell machine. The reason is that one of the unittests 'Cpufreq' took almost 6 minutes to run which is not at all desirable.

This needs further investigation to reduce the time taken for that particular unittest.

**Comment by gkammela** [comment]
1.1 20:00:44:781428578 fwts cpufreq INFO Test 1 of 7: CPU frequency table consistency.
  . . . . .
1.1 20:03:19:308773809 fwts cpufreq RESULT 7 0 0 0

Now that LUV uses latest release of FWTS which include patches like 'cpu/cpufreq : Don't reparse cpu information'  'cpu/cpufreq: Refactor CPU performance tests'  'fwts: scale cpu benchmark results to one second'

http://patchwork.ozlabs.org/patch/474902/
https://lists.ubuntu.com/archives/fwts-devel/2015-May/006114.html
https://lists.ubuntu.com/archives/fwts-devel/2015-May/006147.html

The time taken by  unit test cpufreq is 2  mins 35 seconds and FWTS takes 4 mins 40 secs.. which is much better than results at the time of this issue is opened.

Shall we optimize unit test cpufreq so that it takes only 1-2 minutes?

**Comment by mfleming** [comment]
/cc @ricardon 

If cpufreq now consistently takes less time that it used to on the same machine, that's good. But is cpufreq still the most time consuming test in FWTS? How much more time does it take than the next longest running test?

**Comment by gkammela** [comment]
Yes, the cpufreq is still the most time consuming test in FWTS. The next longest running test is c-states which takes ~1 min and 09 seconds which means cpufreq takes 1 min and 26 seconds more than the time taken by c-states.

**Comment by gkammela** [comment]
fix : https://lists.ubuntu.com/archives/fwts-devel/2015-October/006924.html
 FWTS doesn't include the patch where scaling cpu benchmark results to1 second when this issue is filed and thus FWTS took 6 mins in a 8 core system such as Haswell.

LUV now has latest fwts release which includes Colin's  patch https://lists.ubuntu.com/archives/fwts-devel/2015-May/006147.html  and the time taken by unittest cpufreq went down from 6 mins to 2 mins 35 secs being the longest unitttest in FWTS

With Colin's latest patch(listed as fix here) scaling cpu benchmark results to 25 microseconds without effecting the results in LUV , cpufreq takes about 39 secs to complete saving almost 2 mins ...

with these changes , FWTS takes only 2 mins 21 seconds to run and time taken may vary with the number of cpus in  platform.

**Comment by gkammela** [comment]
LUV will include the new release of bits which has the following commits and thus it reduces the time taken to run BITS. 
https://github.com/biosbits/bits/commit/4eca630bc810361133018a001125c2ef76c39690
https://github.com/biosbits/bits/commit/6331574c7cbbfff313f24563e7211fb2a9d4b809
https://github.com/biosbits/bits/commit/64e95561277d474b420d5e0fb4604c12905db846

with all these patches included in LUV , time taken to test LUV on any platform will be 8-10 mins

**Comment by gkammela** [comment]
Fix is listed above and we no longer face this issue
