### ISSUE TITLE
New test to check the validity of ACPI BGRT tables

### ISSUE THREAD

**Issue by mfleming** [01org/luv-yocto#40]
fwts doesn't include any tests for the ACPI Boot Graphics Resource Table and it would be good to develop a testcase for it since there are a number of buggy tables already seen in the wild which the kernel has to deal with. This task would involve taking the kernel checks in arch/x86/platform/efi/efi-bgrt.c and adding more informative error messages into a testcase for fwts.

**Comment by ricardon** [comment]
FWTS now includes tests for this table.
