### ISSUE TITLE
Improved crash reporting information

### ISSUE THREAD

**Issue by mfleming** [01org/luv-yocto#41]
An automated crash reporting infrastructure, that piggybacks on the current kexec tools work from Ricardo, would be invaluable for gathering debug information. We could use github gists as a place to post such information. Also, simply printing the mailing list and github urls on the screen from the crash handler would give users an option of manually reporting the crash if they didn't want to go down the automated route (because of privacy concerns, for example).

**Comment by meghadey** [comment]
We have impletemented telemetry featurs. Along with pstore and kexec, this should be taken care off
