### ISSUE TITLE
Investigate if CONFIG_DEVTMFS AND CONFIG_DEVTMPFS_MOUNT are needed

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#48]
The kernel options CONFIG_DEVTMFS and CONFIG_DEVTMPFS_MOUNT cause the kernel to populate and mount the /dev directory. However, this is done only until the final rootfs is mounted and an /init file is not found. LUV uses only an initramfs, for which the kernel does not populate /dev. Furthermore, LUV populates the /dev using makedevs at init. Removing this option would reduce the boot time as well as the binary size.

**Comment by gkammela** [comment]
When we remove the options and tested , we have boot failures :
INIT: version 2.88 booting
[    5.551252] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input3
Error opening /dev/fb0: No such device
[    5.820350] psplash (947) used greatest stack depth: 13088 bytes left
Starting udev
Missing devtmpfs, which is required for udev to run
Halting...
INIT: Switching to runlevel: 0
INIT: Sending processes the TERM signal
[    7.168964] cfg80211: Calling CRDA to update world regulatory domain
Sending all processes the TERM signal...
Error opening /dev/fb0: No such device
[   10.320840] cfg80211: Calling CRDA to update world regulatory domain
Sending all processes the KILL signal...
[   13.391833] random: dd urandom read with 13 bits of entropy available
Unmounting remote filesystems...
[   13.474098] cfg80211: Calling CRDA to update world regulatory domain
Deactivating swap...
Unmounting local filesystems...
[   16.624300] cfg80211: Calling CRDA to update world regulatory domain
[   16.808928] ACPI: Preparing to enter system sleep state S5
[   16.811226] reboot: Power down

 and when we have the options and tested :
INIT: version 2.88 booting
[    5.614384] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input3
Error opening /dev/fb0: No such device
[    5.870228] psplash (948) used greatest stack depth: 13088 bytes left
Starting udev

in both the cases  missing /dev/fb0 is the not the issue. 
From the investigation , it seems like the kernel needs both the options to have LUV boot. 
If this issue requires any further investigation , I would try to get more information.

**Comment by ricardon** [comment]
Right, the culprit is "Missing devtmpfs, needed for udev to run". I think
we are ready to close this issue.
