### ISSUE TITLE
Early report of being able to save the test results

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#52]
At the moment, the test manager waits until it has completed all the tests to tell you that there was a problem and it cannot save your test results. This can be frustrating and waste time. It would be better if LUV could test if it is able to save results before running any test. This can warn the tester on whether it needs to take corrective actions.

**Comment by gkammela** [comment]
I think it would be good to parse the serial console messages while LUV is running/booting  to a file and have that file in the luv-results folder would be good to see what is the problem and what causes that problem.

**Comment by ricardon** [comment]
Yes, it would be good in this case, for instance, to show to the user what
are the entries under /dev/disk/by-uuid on why it did not work. Do you have
something else in mind?

**Comment by gkammela** [comment]
Hope a patch that warns about missing partition will help user know why results aren't being saved. I think the next step we can proceed with about saving the results till the unit test it ran  in case of system hang during the boot. Would like to suggest or add more on this ?

**Comment by ricardon** [comment]
On Aug 21, 2015 1:01 PM, "Gayatri Kammela" <notifications@github.com> wrote:
>
> Hope a patch that warns about missing partition will help user know why
results aren't being saved. I think the next step we can proceed with about
saving the results till the unit test it ran in case of system hang during
the boot. Would like to suggest or add more on this ?

I guess we could flush the disk within the test suite loop. Although, how
reliable are the results if the system hangs? This sounds to me more like a
debug option to see how far the tests progress before the hang occurs.
Also, let's write documentation on what to do if you see this message.

**Comment by ricardon** [comment]
Implemented in v2.0-rc3.
