### ISSUE TITLE
Luv image not storing test results to flash

### ISSUE THREAD

**Issue by edTaub** [01org/luv-yocto#53]
I compiled an image using the luv-yocto clone in /home/estaub on luv-build server.

I used my Windows PC and win 32 disk imager to download/write each image to flash drive d:.

I performed a sanity check first using the 3/27 released image from the website. Everything passed on my Linux laptop which UEFI  booted from 3/27 luv flash. Results were stored to flash drive and were visible back on my PC..

When I followed the same approach for the new image, test results failed to get stored.

Today’s results:

1.	re-boot Linux box on latest clone flash, see if error is repeatable.

-	It repeated exactly as before. Took a long time to run, only ran 4 test suites  and put up “not stored message”
-	System now appears to be re-running from bootup??? (I did not touch the system after it completed testing)

2.	look at latest boot flash image using Ubuntu file manager, see if I can see code directories as I saw on 3/27 image.

-	I see two partitions (boot and luv-results; results is empty; boot has boot/, EFI/, initrd, LUV.cer, and vmlinuz icons)

3.	gather system details for Dell laptop and report bug as Matt has requested.
-	Dell Latitude E5540; intel i5-4300 (haswell)  dual core, 1.9GHz,  4GB DRAM

Please let me know if any additional info is required.

Ed Taub

**Comment by ricardon** [comment]
The problem is reproducible in cf3b2ba bits: bump to v1154. The problem happens because the luv-test-manager is unable to the UUID of the luv-results partition. The entry /dev/disk/by-uuid/05D6-1523 is missing.

**Comment by ricardon** [comment]
The issue was not reproducible after merging the latest changes from the master branch of git://git.yoctoproject.org/poky.git.
