### ISSUE TITLE
Chipsec is not able to parse unittest  "chipsec.modules.common.bios_kbrd_buffer" 

### ISSUE THREAD

**Issue by gkammela** [01org/luv-yocto#54]
When we boot LUV  on Haswell machines , sometimes luv.results file shows  ran 70 unittests as summary. The total number of unittests in 5 testsuites are 71. The one that missed running was "chipsec.modules.common.bios_kbrd_buffer" . While the raw folder has the information about this particular unittest By analyzing , it seems that the Chipsec is not able to parse this unittest and that is the reason it is not shown up either in  luv.results or in chipsec parser file.

This issue occurs in cases like if we disturb the keyboard during the boot.  I have tried booting LUV with and without disturbing the keyboard. The issue appears in both cases , except that it appears for sure if we disturb the keyboard.

**Comment by gkammela** [comment]
for additional information , these are the buffer contents (from the raw folder) when Chipsec parses this unittest.
[mem] dword at PA = 0x000000000000041A: 0x001E001E
[mem] dword at PA = 0x000000000000041C: 0x0000001E
[*] Keyboard buffer head pointer = 0x1E (at 0x41A), tail pointer = 0x1E (at 0x41C)
[*] Keyboard buffer contents (at 0x41E):
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
[*] Checking contents of the keyboard buffer..

and these are the buffer contents when Chipsec didn't parse 
[mem] dword at PA = 0x000000000000041A: 0x003C001E
[mem] dword at PA = 0x000000000000041C: 0x8600003C
[*] Keyboard buffer head pointer = 0x1E (at 0x41A), tail pointer = 0x3C (at 0x41C)
[*] Keyboard buffer contents (at 0x41E):
00 86 00 86 00 86 00 86 00 86 00 86 00 86 00 86 |                 
00 86 00 86 00 86 00 86 00 86 00 86 00 86 00 00 |                 
[-] Keyboard buffer tail points inside the buffer (= 0x3C)
    It may potentially expose lengths of pre-boot passwords. Was your password 16 characters long?
[*] Checking contents of the keyboard buffer..

**Comment by ricardon** [comment]
Thanks for the bug report! We are using an updated version of chipsec (1.1.9) in LUV v2.0-rc1. Plus, a problem in the chipsec parser was fixed. Would you mind checking if the problem is still reproducible?

Here is the fix for parser: https://github.com/01org/luv-yocto/commit/3abad308e14974ab09f008f04ccc1e43a7ed586e

**Comment by gkammela** [comment]
I don't see the issue after applying patch/fix . Thanks Ricardo! I think we can close this issue ...

**Comment by ricardon** [comment]
On Aug 21, 2015 1:03 PM, "Gayatri Kammela" <notifications@github.com> wrote:
>
> I don't see the issue after applying patch/fix . Thanks Ricardo! I think
we can close this issue ...

Which patch?

**Comment by gkammela** [comment]
commit 3abad308e14974ab09f008f04ccc1e43a7ed586e

/^ERROR/ {
 	"date +%H:%M:%S:%N" | getline current_time;
 	close ("date +%H:%M:%S:%N")
-	if (test_strs[$2]) {
+	if (test_strs[$2] && !error_strs[$2]) {
 		printf("1.1 %s chipsec %s RESULT 0 0 0 1 0\r\n", current_time, $2);
 		fflush("");
+		error_strs[$2] = 1;
 	}
 }
 
changes to chipsec --luv-test-parser helps fix the issue even if there is any keyboard interrupt

**Comment by ricardon** [comment]
Ah, that makes sense, that commit prevents the parser from reporting
spurious skipped cases when multiple errors are reported. Although, I am
not sure if CHIPSEC specifically looks for keyboard interrupts.

**Comment by gkammela** [comment]
This issue is fixed with the patch https://github.com/01org/luv-yocto/commit/3abad308e14974ab09f008f04ccc1e43a7ed586e
