### ISSUE TITLE
Add ACPI NFIT test suites

### ISSUE THREAD

**Issue by mfleming** [01org/luv-yocto#58]
There are Basic Acceptance Tests (BAT) for ACPI NFIT support floating about in the pmem repository on github. It would be good to add a new recipe to LUV that made use of them.

The source is available in the "ndctl" repo:
https://github.com/pmem/ndctl

To build the tests you'll need to pass "--enable-test --enable-destructive" to "configure", and then you can run the test with "make check" or "ndctl bat" from the installed binary.

**Comment by ricardon** [comment]
Will these tests work even if the system does not have NVDIMMs?

**Comment by mfleming** [comment]
I haven't checked but I doubt they'll pass without having actual physical NVDIMMS on the system. However, it still makes sense to include them since we include a bunch of tests (like for ACPI tables) where the feature may be missing in the firmware and we can just skip the test if so.

**Comment by ricardon** [comment]
This has been implemented with this:
https://github.com/01org/luv-yocto/commit/e3208f9e59628dfd73f3125bf2252643e5b64046
https://github.com/01org/luv-yocto/commit/ae31e95844cc8ef59b1cc7ae4c7bc0e24e1c23c1
https://github.com/01org/luv-yocto/commit/371cfd67d196f1c17b43a27d0d9339796c4068d1
