### ISSUE TITLE
Support deployment of LUV via PXE

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#59]
Deploying LUV via PXE will greatly increase its automation capabilities as it could be easily deployed in network. This entitles the following changes:

1) Write a new recipe that appends the ISO binary to grub-efi (e.g., luv-pxe-live.bb)
2) Modify LUV grub to to use (memdisk)/EFI/BOOT as a prefix
3) Apply change 2) in BITS grub.
4) 3) implies that BITS needs to be built and not simply deployed. The recipe needs to be modified accordingly.

**Comment by meghadey** [comment]
Currently, when we embed the LUV disk image into the grub's bootable image, and try booting bits from the LUV-grub, we get the following error:
error : not a valid root device

On further inspection, in grub-core/loader/efi/chainloader.c, the failure is at 
dev_handle = grub_efidisk_get_device_handle (dev->disk);

The dev-handle in this case is null.
in the  grub_efidisk_get_device_handle function (grub-core/disk/efi/efidisk.c),we have a switch statement to obtain the dev_handle based on disk 'type'.
In this case,we have a memdisk (disk type ='m') which is not covered in the exception,triggering the fault.

Any ideas on how memdisk is supposed to return a dev handle?

**Comment by ricardon** [comment]
On my experiments I am able to obtain the handle. It fails after that, when
trying to obtain the device path in

grub_efi_get_device_path (dev_handle);

The "not a valid root device" is seen if dp, not dev_handle, is null.

Currently, when we embed the LUV disk image into the grub's bootable image,
and try booting bits from the LUV-grub, we get the following error:
error : not a valid root device

On further inspection, in grub-core/loader/efi/chainloader.c, the failure
is at
dev_handle = grub_efidisk_get_device_handle (dev->disk);

The dev-handle in this case is null.
in the grub_efidisk_get_device_handle function
(grub-core/disk/efi/efidisk.c),we have a switch statement to obtain the
dev_handle based on disk 'type'.
In this case,we have a memdisk (disk type ='m') which is not covered in the
exception,triggering the fault.

Any ideas on how memdisk is supposed to return a dev handle?

—
Reply to this email directly or view it on GitHub
<https://github.com/01org/luv-yocto/issues/59#issuecomment-128552539>.

**Comment by ricardon** [comment]
Support for this was implemented with this:
https://github.com/01org/luv-yocto/commit/de4b4ac66860393b931322123791eff185887d73
https://github.com/01org/luv-yocto/commit/2efa324dca7bb1e0c6df11cfcb6e923a446d3ae1
https://github.com/01org/luv-yocto/commit/7fb775a5a13b3c09e7dca7c5e1d66422a9a534d3
https://github.com/01org/luv-yocto/commit/583c9f8930a074536c6bcf22a8cd602890fce098
https://github.com/01org/luv-yocto/commit/37613f36359fe3c924a86db36f0781c75fa7b285
https://github.com/01org/luv-yocto/commit/02c0bc31789197b6ff0654143a4cdf950ee0c19b
https://github.com/01org/luv-yocto/commit/9dbd4f62d0bf3c64bde8efcb9a88462bbd99df6e
https://github.com/01org/luv-yocto/commit/e56435cae987e8d1916b92218037b3b60f359cca
https://github.com/01org/luv-yocto/commit/9e8ee1821baa7b589b3b5f530883fc0ec9696dfb
https://github.com/01org/luv-yocto/commit/b30fc388e31163a1057d892c73aff946a51108e6
https://github.com/01org/luv-yocto/commit/a0f28a80c24117a3a8868d5add0dcce7225286e5
https://github.com/01org/luv-yocto/commit/100ff1a331b34522615b0701c6c85b64af962f12

Regarding the memdisk discussion above, this was resolved by using our own image loading mechanism. For this, we had to modify GRUB to recognize memdisks passed as pointers via comand-line arguments:
https://github.com/01org/luv-yocto/commit/37613f36359fe3c924a86db36f0781c75fa7b285
We reused the mechanism for chainloading images in secure boot. For this, the verification and loading of image had to be done separately:
https://github.com/01org/luv-yocto/commit/7fb775a5a13b3c09e7dca7c5e1d66422a9a534d3
