### ISSUE TITLE
Provide Netconsole support in LUV-live-image

### ISSUE THREAD

**Issue by gkammela** [01org/luv-yocto#62]
Netconsole sends console output to a remote console on another platform. It would be helpful to debug any LUV hangs (specifically during running BITS).Netconsole Allows you to view logs in systems where serial console can't help debugging the issue . It would be good to include netconsole support in live image

**Comment by ricardon** [comment]
Support was implemented with this:
https://github.com/01org/luv-yocto/commit/ab8a6f6caaace80458b7ed52e2168674aec31c91
https://github.com/01org/luv-yocto/commit/61bc31c30e1e21bdd8d1dc0c828a6adeff8e531e
https://github.com/01org/luv-yocto/commit/aa74c183b3a3b0c72db92bf7cd5f21c8b74e8e18
https://github.com/01org/luv-yocto/commit/b18a22473d0265b598fb50a8e3fcc1f7215b1886
https://github.com/01org/luv-yocto/commit/ada969cd825c77a8ba518276c729d50af5989f30
https://github.com/01org/luv-yocto/commit/7cb974d38b210db346774f029e005d6c31c94abb
https://github.com/01org/luv-yocto/commit/0fb5194855f5dd5de3c8b788bb3ff2204f7c7387
https://github.com/01org/luv-yocto/commit/01bf35d052b85e514520827ceadb311ee0795775
https://github.com/01org/luv-yocto/commit/0ca40dd5a9463d552c64f5bc40ea2f21f20e8ae9
https://github.com/01org/luv-yocto/commit/d1c9332258ae67044550f57b81d7a0adc962f9a4
https://github.com/01org/luv-yocto/commit/8336618babcf1e0fff5f8100674add9db4824162
