### ISSUE TITLE
WARNING: QA Issue while building the live image 

### ISSUE THREAD

**Issue by gkammela** [01org/luv-yocto#65]
WARNING: QA Issue...  is seen while attempting to build the live image using bitbake . Though these warnings do not stop bitbake from building live image , there is no clue on what causes these warnings.
below is the log for these warnings..

NOTE: Preparing RunQueue
WARNING: /home/gayuk/luv-yocto/meta-luv/recipes-kernel/linux/linux-yocto-efi-test_4.1.bb.do_compile is tainted from a forced run
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: QA Issue: /home/gayuk/luv-yocto/build/tmp/work/core2-64-oe-linux/efivarfs-test/1.0-r0/packages-split/efivarfs-test/etc/luv/parsers/efivarfs-test is owned by uid 1000, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]
WARNING: QA Issue: /home/gayuk/luv-yocto/build/tmp/work/qemux86_64-oe-linux/chipsec/git-r0/packages-split/chipsec/etc/luv/parsers/chipsec is owned by uid 1000, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]
WARNING: QA Issue: /home/gayuk/luv-yocto/build/tmp/work/qemux86_64-oe-linux/fwts/15.09.00+gitAUTOINC+6843630f98-r0/packages-split/fwts/etc/luv/parsers/fwts is owned by uid 1000, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]

Interesting fact is when the image is cleaned and built it again , these warnings are not seen.
Any idea on what causes these warnings and am I missing any details while building that triggers these warnings ?

**Comment by ricardon** [comment]
A change was added to Poky to warn about host-user contamination when not building from /home (http://patchwork.openembedded.org/patch/102295/). I am not entirely sure why you saw the warnings as you are building from /home. Perhaps not doing a clean build made a difference.

**Comment by ricardon** [comment]
@gkammela has this issue been reproduced in subsequent builds?

**Comment by gkammela** [comment]
Yes , this issue has been reproducible in subsequent builds. Cleaning the live image twice or thrice (including before and after the build)doesn't  reproduce this issue.

**Comment by meghadey** [comment]
So I digged a little into the code, and from meta/classes/insane.bbclass:
home = os.path.join(dest, 'home')
if path == home or path.startswith(home + os.sep):
        return
For all the luv test suites we have:
home: 
/home/megha/luv_kernel/build/tmp/work/core2-64-oe-linux/<test>/1.0-r0/packages-split/home
path:
/home/megha/luv_kernel/build/tmp/work/core2-64-oe-linux/<test>/1.0-r0/packages-split/<test>/etc/luv/parsers/<test>

what yocto expects is to have path as:
 /home/megha/luv_kernel/build/tmp/work/core2-64-oe-linux/<test>/1.0-r0/packages-split/"home"/<test>/etc/luv/parsers/<test>

I don't think doing a clean build will help in this case. 
What I could not find out is how the path variable is being set.

**Comment by ricardon** [comment]
This happens because do_install_runner is not executed as fakeroot and this causes the UID of the owner of the file to be incorrect.
