### ISSUE TITLE
Network support in bits

### ISSUE THREAD

**Issue by gkammela** [01org/luv-yocto#67]
Netconsole support in Luv #62 only provides the debug information about the all the tests except BITS. A patch from Josh Triplett can help us set up the network  and EFI protocols for TCP over IPv4 configuration(like to be able to send messages over Ethernet).
https://github.com/biosbits/bits/commit/f80e7d772c62435bd3dcd435c9d9c1cd51a5273c .
This feature can be enabled in bits so that user can collect the debug information in case of system hangs.. Please input your ideas if there is a better way to include this feature in Bits.

**Comment by meghadey** [comment]
fixed as part of https://lists.01.org/pipermail/luv/2016-December/001394.html
