### ISSUE TITLE
WARNING when building chipsec for ARM

### ISSUE THREAD

**Issue by meghadey** [01org/luv-yocto#72]
On doing a 'bitbake chipsec' when MACHINE=qemuarm64 is selected, the following warning is observed:
WARNING: Error during finalise of /data/sandbox/rneri/luv-yocto-arm/meta-luv/recipes-core/chipsec/chipsec_git.bb

The build fails finally.

**Comment by ricardon** [comment]
This was resolved with https://github.com/01org/luv-yocto/commit/3b54bc2709db8b704bed49b152a7ea78555d9b43
