### ISSUE TITLE
Submit results to central location when booting from network

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#74]
At the moment, when booting from network results are saved only locally and the machine being tested and are accessible only via serial console. An idea is to endow LUV with the capability of submitting results to a central location defined by the user. This location can a remote host accessible via ssh, an FTP server or a web server.

**Comment by ricardon** [comment]
Even a USB stick could be used; this would kill the purpose of booting via the network, though.

**Comment by gkammela** [comment]
https://lists.01.org/pipermail/luv/2016-December/001415.html
