### ISSUE TITLE
DHCP client timeout is too long

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#75]
If the test system is not connected to the network, the DHCP client waits too long to give up and allow the tests to begin. This can give the impression that the system has hung. The timeout needs to be reduced.

Also, there is no indication in the screen of the activites performed when booting.

**Comment by gkammela** [comment]
Setting and reducing the timeout definitely allow the tests to begin faster than before.
#require subnet-mask, domain-name-servers;
#timeout 60;
#retry 60;
 this is snippet of the meta/recipes-connectivity/dhcp/files/dhclient.conf 
Did experiment by setting timeout 60(by un commenting it ) and reducing it to 20 seconds worked!

**Comment by ricardon** [comment]
Great! We need to put this in a bbappend  for the dhcp recipe.

**Comment by gkammela** [comment]
Above referenced commit fixes the issue.
