### ISSUE TITLE
Bump NDCTL to its latest version

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#78]
NDCTL is in version 52. We should bump the version we include in LUV.

**Comment by ricardon** [comment]
NDCTL has been bumped to v50 here: https://github.com/01org/luv-yocto/commit/62e2242765621bd67573cd8f1bcca3d5eb9febd9. It will be bumped to v52 soon.

**Comment by meghadey** [comment]
fixed as part of commit ID: 5a4aea2e9af0cc05b017f49483ec228290450fab
