### ISSUE TITLE
Move nvidmm testing modules out of kernel recipe

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#79]
For modularity, it would be good to move the NVDIMM testing modules out of the kernel recipe. A separate recipe should be created under recipe meta-luv/recipes-core. This separate recipe needs to inherit from module.bbclass which already has all variables needed to access the kernel tree.

This also has the advantage of moving our build artifacts out of the kernel-source tree.

The meta-luv/recipes/core/efivarfs/efivarfs-test can be used as a reference on how to build in-tree kernel components from a separate recipe.

**Comment by meghadey** [comment]
issue fixed 
Commit ID : e3d6456769bb56d97b468b97bf5610ec39ce2967
