### ISSUE TITLE
SSH Hangs on "Entering interactive session" stage

### ISSUE THREAD

**Issue by yamak** [01org/luv-yocto#82]
Hi, 
I built an image with yocto project for Banana Pro board.I am trying to connect port via ssh but I can't. 
Ssh always hangs on "Entering interactive session" stage.When I run ssh command with -v parameter I am getting following log:

> OpenSSH_6.9p1 Ubuntu-2ubuntu0.1, OpenSSL 1.0.2d 9 Jul 2015
> debug1: Reading configuration data /etc/ssh/ssh_config
> debug1: /etc/ssh/ssh_config line 19: Applying options for *
> debug1: Connecting to 10.1.80.41 [10.1.80.41] port 22.
> debug1: Connection established.
> debug1: key_load_public: No such file or directory
> debug1: identity file /home/yusuf/.ssh/id_rsa type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file /home/yusuf/.ssh/id_rsa-cert type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file /home/yusuf/.ssh/id_dsa type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file /home/yusuf/.ssh/id_dsa-cert type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file /home/yusuf/.ssh/id_ecdsa type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file /home/yusuf/.ssh/id_ecdsa-cert type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file /home/yusuf/.ssh/id_ed25519 type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file /home/yusuf/.ssh/id_ed25519-cert type -1
> debug1: Enabling compatibility mode for protocol 2.0
> debug1: Local version string SSH-2.0-OpenSSH_6.9p1 Ubuntu-2ubuntu0.1
> debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1
> debug1: match: OpenSSH_7.1 pat OpenSSH\* compat 0x04000000
> debug1: Authenticating to 10.1.80.41:22 as 'root'
> debug1: SSH2_MSG_KEXINIT sent
> debug1: SSH2_MSG_KEXINIT received
> debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
> debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:XpqS0ZXhoF/OsBmiD8bkpWaZ6Fbk5T3a2Xdq2E8127w
> The authenticity of host '10.1.80.41 (10.1.80.41)' can't be established.
> ECDSA key fingerprint is SHA256:XpqS0ZXhoF/OsBmiD8bkpWaZ6Fbk5T3a2Xdq2E8127w.
> Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added '10.1.80.41' (ECDSA) to the list of known hosts.
> debug1: SSH2_MSG_NEWKEYS sent
> debug1: expecting SSH2_MSG_NEWKEYS
> debug1: SSH2_MSG_NEWKEYS received
> debug1: SSH2_MSG_SERVICE_REQUEST sent
> debug1: SSH2_MSG_SERVICE_ACCEPT received
> debug1: Authentication succeeded (none).
> Authenticated to 10.1.80.41 ([10.1.80.41]:22).
> debug1: channel 0: new [client-session]
> debug1: Requesting no-more-sessions@openssh.com
> debug1: Entering interactive session.

**Comment by ricardon** [comment]
Hi @yamak, did you build a LUV image or a Yocto Project iimage. If you built a LUV image, we don't include an ssh server at the moment is not included in the image. This could explain the behavior that you see.
