### ISSUE TITLE
How to Interpret the CPU MSR Test case failure messages ? 

### ISSUE THREAD

**Issue by srinivasluv** [01org/luv-yocto#87]
Hi LUV Team,

When MSR Tests for CPU Fails, we see the Error output some what like this:
2 unique values
71 CPUs: 1,2,3,4,5,6,7,8,9,16,17,18,19,20,21,22,23,32,33,34,35,36,37,38,39,4
0,41,48,49,50,51,52,53,54,55,64,65,66,67,68,69,70,71,72,73,80,81,82,83,84,85
,86,87,96,97,98,99,100,101,102,103,104,105,112,113,114,115,116,117,118,119
MSR 0x1c8: 0x0
1 CPUs: 0
MSR 0x1c8: 0xc4
[assert] MSR 0x1c9 consistent FAIL
2 unique values
70 CPUs: 1,2,3,4,5,6,7,8,9,16,17,18,19,20,21,22,23,32,33,34,35,36,37,38,39,4
0,41,48,49,50,51,52,53,54,55,65,66,67,68,69,70,71,72,73,80,81,82,83,84,85,86
,87,96,97,98,99,100,101,102,103,104,105,112,113,114,115,116,117,118,119
MSR 0x1c9: 0x0
2 CPUs: 0,64
MSR 0x1c9: 0xd 

Could you help me to know, how to interpret these logs?  How can I make out what really failed from these logs?

Best Regards,
Srinivas BN

**Comment by srinivasluv** [comment]
Hi LUV Team,

Any Updates or pointers on this?

Regards,
Srinivas B.N

**Comment by ricardon** [comment]
Hi Srinivas,

There have been issues with this test. This test essentially checks for the MSRs across CPUs to have consistent values. However, not all the MSRs are expected to have consistent values. Such registers are put in a blacklist. However, there are not black lists for all the CPUs. More CPUs have been added lately. Also, the behavior of BITS has been updated to not run these tests if there is not a blacklist. This is to avoid this very behavior. This is done under a new version of BITS. We will release a new image with this new version this week or early next week.

**Comment by srinivasluv** [comment]
Thanks Ricardon
