### ISSUE TITLE
Please confirm Chipsec.modules.common.spidesc failed

### ISSUE THREAD

**Issue by srinivasluv** [01org/luv-yocto#88]
Hi LUV Team,

If we get the error message like "2)    Chipsec.modules.common.spidesc failed" does it mean SPI BIOS Flash on the platform is not writable or Write protected ?

Best Regards,
Srinivas BN

**Comment by srinivasluv** [comment]
Hi LUV Team, 

Any Updates on this?

Regards,
Srinivas BN

**Comment by ricardon** [comment]
Hi Srinivas, a failure in this test case means that the SPI flash permissions are set to writable. Here is an example:

[*] running module: chipsec.modules.common.spi_desc
[+] imported: chipsec.modules.common.spi_desc
[*] Module path: /usr/lib/python2.7/site-packages/chipsec/modules/common/spi_desc.pyc
[x][ =======================================================================
[x][ Module: SPI Flash Region Access Control
[x][ =======================================================================
[pci] reading B/D/F: 0/31/0, offset: 0xF0, value: 0xFFFFFFFF
[mmio] SPIBAR: 0x00000000FFFFF800 (size = 0x200)
[  463.894801] [chipsec] > IOCTL_RDMMIO
[  463.894801] [chipsec] > IOCTL_RDMMIO
[mmio] 0xFFFFF800 + 0x00000050 = 0xFFFFFFFF
[*] FRAP = 0xFFFFFFFF << SPI Flash Regions Access Permissions Register (SPIBAR + 0x50)
    [00] BRRA             = FF << BIOS Region Read Access 
    [08] BRWA             = FF << BIOS Region Write Access 
    [16] BMRAG            = FF << BIOS Master Read Access Grant 
    [24] BMWAG            = FF << BIOS Master Write Access Grant 
[*] Software access to SPI flash regions: read = 0xFF, write = 0xFF
[-] Software has write access to SPI flash descriptor

[-] FAILED: SPI flash permissions allow SW to write flash descriptor

**Comment by srinivasluv** [comment]
Thanks  Ricardo  ! This explains
