### ISSUE TITLE
fwts: EFI MEMMAP not enbled

### ISSUE THREAD

**Issue by gkammela** [01org/luv-yocto#90]
A  bug was found  in a couple of platforms and though it is not halting/ freezing the system but it takes way too much time to finish the rest of the test suites. When debugging the issue via network(netconsole) this issue was found in fwts and the reason was "EFI MEMMAP not enabled". This issue was found in the platforms with HP Elitebook 840 and Lenovo thinkpad. 
## bug report

[  116.659047]   [+] uefirttime... passed
[  116.927787] efi: EFI_MEMMAP is not enabled.
[  116.931451] BUG: unable to handle kernel NULL pointer dereference at           (null)
[  116.938744] IP: [<fffffffeffbd03f9>] 0xfffffffeffbd03f9
[  116.943302] PGD 131cd8063 PUD 0
[  116.946288] Oops: 0000 [#1] SMP
[  116.949466] Modules linked in: efi_runtime(O) chipsec(O) netconsole e1000e [last unloaded: efi_runtime]
[  116.957822] CPU: 1 PID: 1988 Comm: fwts Tainted: G           O    4.6.0-yocto-standard #1
[  116.965312] Hardware name: Hewlett-Packard HP EliteBook 840 G1/198F, BIOS L71 Ver. 01.20 07/28/2014
[  116.973451] task: ffff88012cbfac00 ti: ffff8800353a8000 task.ti: ffff8800353a8000
[  116.979543] RIP: 0010:[<fffffffeffbd03f9>]  [<fffffffeffbd03f9>] 0xfffffffeffbd03f9

**Comment by ricardon** [comment]
Do we still see this? I feel that the problem was with a machine illegally accessing boot services memory regions as well as a bug in our in-kernel mechanism to detect such accesses (this should be fixed by now in Sai's latest version).

**Comment by meghadey** [comment]
This is fixed as part of Sai's  illegal memory access patch
