### ISSUE TITLE
Write LUV messages to a console and/or debug file

### ISSUE THREAD

**Issue by meghadey** [01org/luv-yocto#96]
Currently, we only use the graphical manager(psplash currently) to display certain messages to the user. Hence, someone with access to only serial console or netconsole will not know what is going on. We need to write these messages to a console and/or a debug file.

**Comment by ricardon** [comment]
Agreed, we do this in many places. A good solution would be to have somewhere a function (e.g., LUV_print or LUV_msg) that takes care of printing to the available outlets.

**Comment by meghadey** [comment]
Patch that fixes this issue can be found here:
https://lists.01.org/pipermail/luv/2018-January/002488.html
