### ISSUE TITLE
LUV : No space left on device

### ISSUE THREAD

**Issue by gkammela** [01org/luv-yocto#99]
Recent findings while testing custom builds on various platforms shows that 3 out 10 builds hit the 'No space left on device'. At first , this issue was seen only on real hardware but then it appears it QEMU too.

here is the log:
tee: /mnt/luv-storage/luv-results-2016-11-18--23-42-36/parsed/chipsec: No space left on device
[   64.949402]   [+] chipsec.modules.common.bios_kbrd_buffer... passed
[   65.180382]   [+] chipsec.modules.common.bios_smi... passed
awk: cmd. line:141: (FILENAME=- FNR=58) fatal: print to "/mnt/luv-storage/luv-results-2016-11-18--23-42-36//luv.html" failed (No space left on device)

and the following keeps printing after each unittest.
awk: cmd. line:97: (FILENAME=- FNR=1) warning: file flush of `/mnt/luv-storage/luv-results-2016-11-18--23-42-36//luv.html' failed (No space left on device).

**Comment by ricardon** [comment]
Hmmm. This might indicate that we are either 1) underestimating the amount
of storage is needed to store results or 2) the logic we use to abort if
there is not enough space is buggy. We should discover these issues even
before attempting to run any test case. Did you use the same USB stick
repeatedly to hit this issue?

**Comment by gkammela** [comment]
I did use the same USB disk, but the issue hits on the second run itself. With 16MB allocated for luv-results partition and each test results takes up to 1.1MB, we've got plenty of storage left and this "no space left shouldn't appear until the 14/15 runs.

Interesting fact is we hit the same issue in the QEMU, where we don't have partitions to store the results.

**Comment by ricardon** [comment]
Are you running a diskboot or a netboot image? If you are running a
diskboot image in QEMU you do have the partitions to save the results.
However, you need to exit QEMU gracefully to give it a chance to flush
files to disk. You can exit gracefully by issuing poweroff from the command
line.

**Comment by gkammela** [comment]
Yes , I am running diskboot image and I exit QEMU via Ctrl +c. Now, I know QEMU has partitions to save results. Thanks ! @ricardon

The results partition does get full, as bits in parsed directory alone occupies 11MB when we run LUV without BITS and thus triggering the "no space left" logic. This issue in bits is reported by  @prakhya 

A patch has been submitted to the luv@lists.01.org to resolve this bug.

**Comment by gkammela** [comment]
Even with the patch fixes the 11MB bits file issue , I still see the same message "no space left on device" . This issue needs more debugging than expected. Any thoughts @ricardon ?

**Comment by ricardon** [comment]
Are you certain that you still see the 11MB filesize? I tested your patch and it works for me. Could you be using an unpatched version?

**Comment by gkammela** [comment]
sorry for the noise! I realized I was using unpatched version as I recently did rebase some of my patches.  Applying the patch doesn't reproduce the error

**Comment by gkammela** [comment]
https://lists.01.org/pipermail/luv/2016-December/001433.html
